name: Build & Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get sha short
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload to Panel
        uses: rexlmanu/pterodactyl-upload-action@v1
        with:
          panel-host: ${{ secrets.PANEL_URL }}
          api-key: ${{ secrets.API_KEY }}
          server-id: ${{ secrets.SERVER_ID }}
          source: "./bot/build/libs/WoolStats.jar"
          target: "./"

      - name: Restart Bot
        uses: outsparkled/pterodactyl-power-action@v0.1.0
        with:
          panel-url: ${{ secrets.PANEL_URL }}
          server-id: ${{ secrets.SERVER_ID }}
          bearer-token: ${{ secrets.API_KEY }}
          power-action: restart

      - name: Webhook to Inform Changes
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "`${{ steps.vars.outputs.sha_short }}` - ${{ github.event.head_commit.message }}"